lux-group/lib-uri-templates

index.js
* Add a URI template for a new endpoint
Parent PR: https://github.com/brandsExclusive/www-le-admin/pull/301
=> [Leng 237] - Add room type amenities

index.js
=> add: giftcard_terms_and_conditions

index.js
Support retrieving schedules by brand, and patching offer by brand
https://github.com/brandsExclusive/svc-offer/pull/254
=> Add brand parameters to offer calls

index.js, package.json
https://github.com/brandsExclusive/svc-ee-offer/pull/92
=> Add hero_assignment resource

index.js
Add offer service inventory related URI templates
=> Add offer service inventory related URI templates

package.json
=> Increase version to 0.3.2

index.js, package.json
Changed inventory public status route template
This route is to know the inventory limit has been reached.
=> Changed inventory public status route template

index.js
https://github.com/brandsExclusive/svc-public-offer/pull/62
=> add locations query for public offers

index.js, package.json
=> add uri-template for offers_search route

index.js, package.json
=> [ST-165] add /offers-content route

index.js
https://aussiecommerce.atlassian.net/secure/RapidBoard.jspa?rapidView=47&projectKey=LENG&modal=detail&selectedIssue=LENG-881
This PR adds about us
=> [LENG-881] add about us

package.json
=> release version 0.5.3

index.js
This PR adds objectID as an optional param to the public offers query
=> add objectID

index.js
See also https://github.com/brandsExclusive/svc-public-offer/pull/124
=> Add all_packages param to public offer template

index.js, package.json
Add flight fare rules template
=> Add flights fare rules route

src/index.ts
Add region to the flights route
=> Add region to single cheapest flights

package.json, src/index.ts, yarn.lock
This PR is to add included-guest
And fixes Github security alert by updating mocha
=> Included guests

src/index.ts
=> Included all addons

package.json, src/index.ts, test/test.ts
Also make query param optional
=> region query update

src/index.ts
https://aussiecommerce.atlassian.net/browse/LEE-257?atlOrigin=eyJpIjoiNGZiMTY3OThkNzBmNDI0N2JlYzQ4MjZjMWVjYWJmNTQiLCJwIjoiaiJ9
svc-public-offer pr:
https://github.com/brandsExclusive/svc-public-offer/pull/369
Add strategy_applied tag to decide which strategy would be used to query and process offers.
=> add strategy_applied tag for public_offers

package.json
=> update version for ffc6c9e commit

package.json, src/index.ts
Adds the only_ids param for public offers end point
=> Add only_ids param

src/index.ts
Required to implement le plus filters on offer lists
=> Adding benefit types to offers

src/offer.ts
This PR adds a new route for bedbank
=> Bedbank offer

package.json, src/offer.ts
https://aussiecommerce.atlassian.net/browse/KAN-819?atlOrigin=eyJpIjoiZDhiOGMxMWQwNDU5NGUxODhlYWNjYTY1NDdjYTg5YWQiLCJwIjoiaiJ9
Public offer pr: lux-group/svc-public-offer#556
Public offer feed pr: https://github.com/lux-group/svc-public-offer-feed/pull/117
=> [KAN-819] Noindex Exclude Offer From Feed

package.json
To make it consistent with npm
=> Bump version v0.11.10

package.json, src/offer.ts
https://developer.expediapartnersolutions.com/documentation/rapid-shopping-docs-2-4/#/Shopping/get_properties_availability
2 adults, one 9-year-old and one 4-year-old would be represented by occupancy=2-9,4.
A multi-room request to lodge an additional 2 adults would be represented by occupancy=2-9,4&occupancy=2
=> [AO-4] add occupancy parameter

package.json, src/offer.ts
Add `/api/v2/public-offers/list` which will be used to serve a list of offer ids that match the search criteria.
=> Add /api/v2/public-offers/list

package.json, src/offer.ts
Add search params to v1 public offers endpoint
=> Add search params to v1 public offers

package.json, src/offer.ts
Related https://github.com/lux-group/svc-public-offer/pull/655
=> Add search params in offer filter query

src/offer.ts
Pass sales channel info as below via`medium` to BE, values like:
`ios`
`android`
`website`
=> added medium

src/offer.ts
=> SP-450: search for properties

package.json, src/offer.ts
Add brand to a param list of `publicOfferList`
`"/api/v2/public-offers/list{?placeIds,occupancy,checkIn,checkOut,region,offerType,brand}"`
=> Add brand as a param for publicOfferList template

src/offer.ts, src/order.ts, test/test.ts
This is necessary to solve:
https://aussiecommerce.atlassian.net/wiki/spaces/TEC/pages/1862467626/Resolve+addons+performance+issues
=> [EXP-30]: Add remove_addons filter on orders

package.json, src/flight.ts
Jira case - https://aussiecommerce.atlassian.net/browse/FLY-342
Added new API end point to the svc flight service to check whether bed bank property is blocked or not.
=> [ FLY-342 ] - Added flight_is_block_bedbank API endpoint

package.json, src/offer.ts
Also added some other missing params that customer portal sends.
=> Add `sortBy` param to offer list endpoints

package.json, src/offer.ts
https://aussiecommerce.atlassian.net/browse/CONTB-395
=> feat(sales-environment): add package type for check availability

package.json, src/content.ts
[Ticket](https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106?selectedIssue=OPEX-310)
https://github.com/lux-group/lib-regions/pull/212
https://github.com/lux-group/svc-discovery/pull/252
https://github.com/lux-group/svc-graphql/pull/193
https://github.com/lux-group/lib-types/pull/313
We are providing priority phone numbers for high value orders, I'm adding those similar to regions array but in a separate module to exclude any issues. I declared new api endpoint in lib-uri-templates it will be used by svc-discovery to serve data for svc-graphql.
=> [OPEX-310] add priority phone numbers

package.json, src/content.ts
I'm fixing url that I just added, I used underscores instead of dash.
=> [OPEX-310] fix url underscore

package.json, src/index.ts, src/tour.ts
This adds a route to the new tours service, to get further details about the reservation.
This is an example of the route
https://test-api.luxuryescapes.com/api/v2/tours/reservations/ca0e59cb-fbd9-49a6-929f-8e375aedc514/snapshot
=> TOUR-342 New tours need info from svc-tour

package.json, src/index.ts
Left out something on 
https://github.com/lux-group/lib-uri-templates/pull/153
=> Include tour in exported templates

package.json, src/offer.ts
This patch is adding the cancellation policies filter parameter into the offer list API.
=> CRO-452 add cancellation policies filter parameter into offer list API

package.json, src/tour.ts
For this new route
https://github.com/lux-group/svc-tour/pull/139/files
=> TOUR-417 Add season compare route

package.json, src/offer.ts
This PR adds the `amenities` query parameter into the public offer list API.
=> [CRO-474] Add amenities parameter into offer list API.

package.json, src/offer.ts
https://aussiecommerce.atlassian.net/browse/CONTB-682
=> feat(traders): add a new endpoint for traders

package.json, src/index.ts, src/referral.ts
=> Add referral uri's

package.json, src/referral.ts
=> MP-330-Fix-Query-Params

package.json, src/offer.ts, test/test.ts
This is the PR for the new offer extra endpoint.
=> [CRO-535] Add the new offer extra endpoint for the offer views today.

src/search.ts
Add the definition of the new endpoint which provides the top sale places based on the user's geolocation.
=> [CRO-624] Add the search endpoint for the top sale places by user geolocation

package.json
Bump the version number for the PR #174
=> [CRO-624] Bump the package.json version.

package.json, src/offer.ts
Jira: [CRO-619](https://aussiecommerce.atlassian.net/jira/software/projects/CRO/boards/114?selectedIssue=CRO-619)
This patch is removing the cancellation policies filter parameter into the offer list API.
=> [CRO-619]: Remove cancellation policies filter parameter into offer list API

package.json, src/search.ts
This PR moves the hotel trending and top-selling places to the new routes.
=> [CRO-624] Move hotel related places' endpoint to new route.

src/reservation.ts
Fixes [FLY-1515](https://aussiecommerce.atlassian.net/browse/FLY-1515)
Update lib-uri-templates to include no_of_adults in the tour enquiry endpoint
=> [FLY-1515]Add no_of_adults to lib-uri-templates

package.json, src/bedbank.ts
https://aussiecommerce.atlassian.net/browse/CONTB-1075
=> feat(bedbank): add calendar url

package.json, src/offer.ts
https://aussiecommerce.atlassian.net/browse/CONTB-1108
=> feat(preview): add preview mode

package.json
Update version to `1.7.34`, a change that was missed in #185 .
=> fix: Update version

src/reservation.ts
https://github.com/lux-group/svc-reservation/pull/1870
adding inclusions-catalogue/categories to uri-templates
=> [OPEX-1027] add inclusions-catalogue categories to links

package.json
Bumping version
https://github.com/lux-group/lib-uri-templates/pull/187
=> bump version 1.7.35

src/search.ts, test/test.ts
This PR will add search list to `lib-uri-templates`.
=> [FEAT] Add search list

src/bedbank.ts
JIRA: https://aussiecommerce.atlassian.net/browse/CONTB-1578
=> feat(bedbank-calendar): add additional query param roomId

package.json, src/content.ts
Jira: https://aussiecommerce.atlassian.net/browse/LOYAL-124
- Added template for priority phone numbers by type where you can query a priority phone number based on region, brand and type (luxplus, cruises, support assistant, etc)
=> [LOYAL-124] Priority phone numbers by type

package.json, src/content.ts
Reverts lux-group/lib-uri-templates#199
=> Revert "[LOYAL-124] Priority phone numbers by type"

package.json, src/order.ts
Add `status` to orders template filter to support Mobile team on building `My Escapes`
=> [JUP-6721] Add `status` to orders template filter

package.json, src/offer.ts
For context, see the following slack thread: https://luxgroup-hq.slack.com/archives/C05RJK6B7NY/p1713140449821079
=> [NO-JIRA] refactor: remove vendor_offers template

package.json, src/affilate.ts, src/index.ts
Add endpoints for the Affiliate sites (just covering the 'site' endpoint atm)
=> feat(affiliate-site-links): [GR-3206] Add initial affiliate uris

package.json, src/offer.ts
https://aussiecommerce.atlassian.net/browse/HC-200
Add source to public-offers uri's
=> [HC-200] add: source query param to public-offers uri

package.json, src/offer.ts
https://aussiecommerce.atlassian.net/browse/HC-307
=> feat(offer): slug

package.json
Changed license to more appropriate one
=> chore: Updated license
